Controllers/OrderDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Nice_Admin_Backened.Models;
using System.Data.SqlClient;
using System.Data;

namespace Nice_Admin_Backened.Controllers
{
    public class OrderDetailController : Controller
    {
        private IConfiguration configuration;

        public void OrderDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_Order_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                OrderDropDownModel orderDropDownModel = new OrderDropDownModel();
                orderDropDownModel.OrderID = Convert.ToInt32(data["OrderID"]);
                orderList.Add(orderDropDownModel);
            }
            ViewBag.OrderList = orderList;
        }

        public void ProductDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_Product_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<ProductDropDownModel> productList = new List<ProductDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                ProductDropDownModel productDropDownModel = new ProductDropDownModel();
                productDropDownModel.ProductID = Convert.ToInt32(data["ProductID"]);
                productDropDownModel.ProductName = (data["ProductName"]).ToString();
                productList.Add(productDropDownModel);
            }
            ViewBag.ProductList = productList;
        }
        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userlist = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userlist.Add(userDropDownModel);
            }
            ViewBag.UserList = userlist;
        }
        public OrderDetailController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult OrderDetailAddEditForm(int OrderDetailID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_OrderDetail_SelectByID";
            command.Parameters.AddWithValue("@OrderDetailID", OrderDetailID);
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            OrderDetailModel orderDetailModel = new OrderDetailModel();

            foreach (DataRow dataRow in table.Rows)
            {
                orderDetailModel.OrderDetailID = Convert.ToInt32(@dataRow["OrderDetailID"]);
                orderDetailModel.OrderID = Convert.ToInt32(@dataRow["OrderID"]);
                orderDetailModel.ProductID = Convert.ToInt32(@dataRow["ProductID"]);
                orderDetailModel.Quantity = Convert.ToInt32(@dataRow["Quantity"]);
                orderDetailModel.Amount = Convert.ToDecimal(@dataRow["Amount"]);
                orderDetailModel.TotalAmount = Convert.ToDecimal(@dataRow["TotalAmount"]);
                orderDetailModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }
            OrderDropDown();
            ProductDropDown();
            UserDropDown();
            return View("OrderDetailAddEditForm" , orderDetailModel);
        }

        //SERVER SIDE 
        [HttpPost]
        public IActionResult OrderDetailSave(OrderDetailModel orderDetailModel)
        {
            if (orderDetailModel.OrderDetailID <= 0)
            {
                ModelState.AddModelError("OrderDetailID", "A valid OrderDetail is required.");
            }

            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (orderDetailModel.OrderDetailID == null)
                {
                    command.CommandText = "PR_OrderDetail_Insert";
                }
                else
                {
                    command.CommandText = "PR_OrderDetail_Update";
                    command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = orderDetailModel.OrderDetailID;
                }
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = orderDetailModel.OrderID;
                command.Parameters.Add("@ProductID", SqlDbType.Int).Value = orderDetailModel.ProductID;
                command.Parameters.Add("@Quantity", SqlDbType.Int).Value = orderDetailModel.Quantity;
                command.Parameters.Add("@Amount", SqlDbType.Decimal).Value = orderDetailModel.Amount;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = orderDetailModel.TotalAmount;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = orderDetailModel.UserID;
                command.ExecuteNonQuery();
                return RedirectToAction("OrderDetailsListPage");
            }
            OrderDropDown();
            ProductDropDown();
            UserDropDown();
            return View("OrderDetailAddEditForm", orderDetailModel);
        }

        public IActionResult OrderDetailDelete(int OrderDetailID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_OrderDetail_Delete";
                command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = OrderDetailID;
                command.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("OrderDetails");
        }
        public IActionResult OrderDetailsListPage()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_OrderDetail_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }
    }
}

Views/OrderDetail/OrderDetailAddEditForm.cshtml
@model Nice_Admin_Backened.Models.OrderDetailModel


<main id="main" class="main">

    <div class="pagetitle">
        <h1>Form Elements</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Forms</li>
                <li class="breadcrumb-item active">Elements</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-8">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">OrderDetail Add/Edit Form</h5>

                        <!-- Product Form Elements -->
                        <form asp-controller="OrderDetail" asp-action="OrderDetailSave">
                            <input type="hidden" asp-for="OrderDetailID" />
                            <div class="row mb-3">
                                <label for="inputOrderId" class="col-sm-3 col-form-label">OrderId</label>
                                <div class="row mb-3">
                                    <div class="col-sm-8">
                                        <select class="form-control" asp-for="OrderID" asp-items="@(new SelectList(ViewBag.OrderList, "OrderID", "OrderID"))">
                                            <option value="">Select Order</option>
                                        </select>
                                        <span asp-validation-for="OrderID" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <label for="inputProductPrice" class="col-sm-3 col-form-label">Product Quantity</label>
                                <div class="col-sm-9">
                                    <input type="number" asp-for="Quantity" class="form-control" id="inputQuantity" placeholder="Enter Quantity">
                                    <span asp-validation-for="Quantity" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <label for="inputProductCode" class="col-sm-3 col-form-label">Amount</label>
                                <div class="col-sm-9">
                                    <input type="number" asp-for="Amount" class="form-control" id="inputAmount" placeholder="Enter Amount">
                                    <span asp-validation-for="Amount" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <label for="inputDescription" class="col-sm-3 col-form-label">Total Amount</label>
                                <div class="col-sm-9">
                                    <input type="number" asp-for="TotalAmount" class="form-control" id="inputTotalAmount" placeholder="Enter Total Amount">
                                    <span asp-validation-for="TotalAmount" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputUserId" class="col-sm-3 col-form-label">ProductId</label>
                                <div class="col-sm-9">
                                    <select class="form-control" id="inputProductId" asp-for="ProductID" asp-items="@(new SelectList(ViewBag.ProductList, "ProductID", "ProductName"))">
                                        <option value="">Select ProductId</option>
                                    </select>
                                    <span asp-validation-for="ProductID" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="inputUserId" class="col-sm-3 col-form-label">UserId</label>
                                <div class="col-sm-9">
                                    <select class="form-control" id="inputUserId" asp-for="UserID" asp-items="@(new SelectList(ViewBag.UserList, "UserID", "UserName"))">
                                        <option value="">Select UserId</option>
                                    </select>
                                    <span asp-validation-for="UserID" class="text-danger"></span>
                                </div>
                            </div>


                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <button type="reset" class="btn btn-secondary">Reset</button>
                            </div>
                        </form><!-- End Product Form Elements -->

                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->
@section Scripts {
    @{
        Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/OrderDetail/OrderDetailsListPage.cshtml
@using System.Data
@model System.Data.DataTable

<main id="main" class="main">
    <div class="pagetitle">
        <h1>OrderDetail</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-controller="Home" asp-action="Index">
                        <i class="bi bi-house-door"></i>
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a>Order List</a>
                </li>
            </ol>
        </nav>
        <div class="d-flex justify-content-end align-items-center">
            <div>
                <a class="btn btn-outline-primary" asp-controller="OrderDetail" asp-action="OrderDetailAddEditForm"><i class="bi bi-plus-lg"></i>&nbsp;Add OrderDetail</a>
            </div>
        </div>
    </div><!-- End Page Title -->

    <table class="table table-hover table-header-fixed">
        <thead>
            <tr>
                <th scope="col">OrderDetailId</th>
                <th scope="col">OrderId</th>
                <th class="col">ProductId</th>
                <th class="col">Quantity</th>
                <th class="col">Amount</th>
                <th class="col">TotalAmount</th>
                <th class="text-center">UserID</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody id="sample_2">
            <span class="text-danger">@TempData["ErrorMessage"]</span>
            @foreach (DataRow dataRow in Model.Rows)
            {
                <tr>
                    <td>@dataRow["OrderDetailId"]</td>
                    <td>@dataRow["OrderId"]</td>
                    <td>@dataRow["ProductId"]</td>
                    <td>@dataRow["Quantity"]</td>
                    <td>@dataRow["Amount"]</td>
                    <td>@dataRow["TotalAmount"]</td>
                    <td>@dataRow["UserID"]</td>
                    <td class="text-center">
                        <a class="btn btn-outline-success btn-xs" asp-controller="OrderDetail" asp-action="OrderDetailAddEditForm" asp-route-OrderDetailID="@dataRow["OrderDetailID"]">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a href="/OrderDetail/OrderDetailDelete?OrderDetailID=@dataRow["OrderDetailID"]" class="btn btn-outline-danger btn-xs">
                            <i class="bi bi-x"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>