Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using Microsoft.Extensions.Configuration;
using Nice_Admin_Backened.Models;
using System.Text.Json.Serialization;
using System.Runtime.InteropServices;
using System.Xml;
using Newtonsoft.Json;

namespace Nice_Admin_Backened.Controllers
{
    public class CountryController : Controller
    {

        #region configuration
        private readonly IConfiguration _configuration;
        
        public CountryController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #endregion

        #region CountryListPage 
        public IActionResult CountryListPage()
        {
            string connectionString = this._configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_LOC_Country_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View("CountryListPage", table);
        }
        #endregion

        #region Delete
        public IActionResult DeleteCountry(int CountryID)
        {
            string connectionstr = _configuration.GetConnectionString("ConnectionString");
            using (SqlConnection conn = new SqlConnection(connectionstr))
            {
                conn.Open();
                using (SqlCommand sqlCommand = conn.CreateCommand())
                {
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.CommandText = "PR_LOC_Country_Delete";
                    sqlCommand.Parameters.AddWithValue("@CountryID", CountryID);
                    sqlCommand.ExecuteNonQuery();
                }
            }
            return RedirectToAction("CountryListPage");
        }
        #endregion

        #region CountryAddEdit
        public IActionResult CountryAddEdit(int CountryID)
        {
            string connectionString = this._configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_LOC_Country_SelectByPK";
            command.Parameters.AddWithValue("@CountryID", CountryID);
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            CountryModel countryModel = new CountryModel();

            foreach (DataRow dataRow in table.Rows)
            {
                countryModel.CountryID = Convert.ToInt32(@dataRow["CountryID"]);
                countryModel.CountryName = @dataRow["CountryName"].ToString();
                countryModel.CountryCode = @dataRow["CountryCode"].ToString();
            }
            return View("CountryAddEdit", countryModel);
        }
        #endregion

        #region CountrySave
        [HttpPost]
        public IActionResult CountrySave(CountryModel countryModel)
        {
            // Validate the CountryID to ensure it's provided
            if (countryModel.CountryID <= 0 && string.IsNullOrWhiteSpace(countryModel.CountryName))
            {
                ModelState.AddModelError("CountryID", "A valid CountryID is required.");
                ModelState.AddModelError("CountryName", "Country Name is required.");
            }

            if (ModelState.IsValid)
            {
                string connectionString = this._configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;

                    if (countryModel.CountryID <= 0 || countryModel.CountryID == null ) // Insert case
                    {
                        command.CommandText = "PR_LOC_Country_Insert";
                        command.Parameters.Add("@CreatedDate", SqlDbType.DateTime).Value = DateTime.Now;

                    }
                    else // Update case
                    {
                        command.CommandText = "PR_LOC_Country_Update";
                        command.Parameters.Add("@CountryID", SqlDbType.Int).Value = countryModel.CountryID;
                        command.Parameters.Add("@ModifiedDate", SqlDbType.DateTime).Value = DateTime.Now;

                    }

                    command.Parameters.Add("@CountryName", SqlDbType.NVarChar).Value = countryModel.CountryName;
                    command.Parameters.Add("@CountryCode", SqlDbType.NVarChar).Value = countryModel.CountryCode;

                    command.ExecuteNonQuery();
                }
                return RedirectToAction("CountryListPage");
            }
            return View("CountryAddEdit", countryModel);
        }
        #endregion

    }
}

Views/Country/CountryAddEdit.cshtml
@model Nice_Admin_Backened.Models.CountryModel


<main id="main" class="main">

    <div class="pagetitle">
        <h1>Form Elements</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Forms</li>
                <li class="breadcrumb-item active">Elements</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Country Add/Edit Form</h5>
                        <form asp-controller="Country" asp-action="CountrySave">
                            <input type="hidden" asp-for="CountryID" />
                            <div class="mb-3 row">
                                <label for="inputCountryName" class="col-sm-3 col-form-label">CountryName</label>
                                <div class="col-sm-9">
                                    <input type="text" asp-for="CountryName" class="form-control" id="inputCountryName" placeholder="Enter CountryName">
                                    <span asp-validation-for="CountryName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <label for="inputCountryCode" class="col-sm-3 col-form-label">CountryCode</label>
                                <div class="col-sm-9">
                                    <input type="text" asp-for="CountryCode" class="form-control" id="inputCountryCode" placeholder="Enter CountryCode">
                                    <span asp-validation-for="CountryCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <button type="reset" class="btn btn-secondary">Reset</button>
                            </div>
                        </form>


                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Country/CountryListPage.cshtml
@using System.Data
@model System.Data.DataTable

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Country</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-controller="Home" asp-action="Index">
                        <i class="bi bi-house-door"></i>
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a>Country List</a>
                </li>
            </ol>
        </nav>
        <div class="d-flex justify-content-end align-items-center">
            <div>
                <a class="btn btn-outline-primary" asp-controller="Country" asp-action="CountryAddEdit"><i class="bi bi-plus-lg"></i>&nbsp;Add Country</a>
            </div>
        </div>
    </div><!-- End Page Title -->

    <table class="table table-hover table-header-fixed">
        <thead>
            <tr>
                <th scope="col">Country Name</th>
                <th scope="col">Country Code</th
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody id="sample_2">
            <span class="text-danger">@TempData["ErrorMessage"]</span>
            @foreach (DataRow dataRow in Model.Rows)
            {
                <tr>
                    <td>@dataRow["CountryName"]</td>
                    <td>@dataRow["CountryCode"]</td>
                    <td class="text-center">
                        <a class="btn btn-outline-success btn-xs" asp-controller="Country" asp-action="CountryAddEdit" asp-route-CountryID=@dataRow["CountryID"]>
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <!-- Delete Button with SweetAlert -->
                        <a href="javascript:void(0)" onclick="confirmDelete('@Url.Action("DeleteCountry", "Country", new { CountryID = dataRow["CountryID"] })')" class="btn btn-outline-danger btn-xs">
                            <i class="bi bi-x"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>

<script>
    function confirmDelete(deleteUrl) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = deleteUrl; // Redirect to the delete URL if confirmed
            }
        });
    }
</script>